version: "3"
services:
  postgres_db:
    image: postgres
    hostname: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend_db
    volumes:
      - ./mnt/data/postgres/data:/var/lib/postgresql/data
      - ./mnt/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: localhost:5001/backend-img
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    volumes:
      - ./mnt/data/jobs:/data/jobs
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: unless-stopped

  worker:
    image: localhost:5001/worker-img
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
    volumes:
      - ./mnt/data/jobs:/data/jobs
    deploy:
      replicas: 2

  scheduler:
    image: localhost:5001/scheduler-img
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - worker

  webapp:
    image: localhost:5001/webapp-img
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - backend
